version: "3.9"

services:
  workout_organizer_api:
    container_name: workout_organizer_api
    image: nejj/workout_organizer_api:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@workout_organizer_db:5432/postgres
    depends_on:
      - workout_organizer_db
  workout_organizer_db:
    container_name: workout_organizer_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}